### ISSUE TITLE
WHY sudo installation?

### ISSUE THREAD

**Issue by rxx** [fishworks/gofish#115] opened 2018-10-15 19:01 UTC
I like the idea of Gofish but what's wrong with it? Why it asks my password and want to be on my root folder instead of home one?
I realy don't like it.
How can I put everything in `$HOME/.gofish`

**Comment by imander** [comment] 2018-12-21 22:01
Agreed.  I like this project and was going to use it in a CI pipeline but have since abandoned it due to the sudo requirements.

**Comment by bacongobbler** [comment] 2018-12-21 22:31
Change the install path from /usr/local to $HOME for now. Contributions to make it possible to install packages in $HOME would be welcome.

For MacOS, you need to make the changes here (for Windows/Linux, change it in _windows.go or _linux.go): https://github.com/fishworks/gofish/blob/master/home_darwin.go

**Comment by bacongobbler** [comment] 2018-12-22 03:08
I’m going to close this as it was entirely intended by design to be a systems package manager like homebrew/apt/yum and I do not intend to implement this functionality.

If someone wants to make this an opt-in feature flag for `gofish init`, I’d love a PR.

**Closed by bacongobbler** 2018-12-22 03:08 UTC
